const D=window.RESEARCH_DATA;const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let state={domain:"全部",model:"all",formula:"all",source:"all",query:""};
function renderDomains(){const groups=["全部",...new Set(D.domains.map(x=>x.group))];$("#domainFilters").innerHTML=groups.map(g=>`<button class="${state.domain===g?'active':''}" data-domain="${esc(g)}">${esc(g)}</button>`).join("");const q=state.query.toLowerCase();const rows=D.domains.filter(x=>(state.domain==="全部"||x.group===state.domain)&&JSON.stringify(x).toLowerCase().includes(q));$("#domainGrid").innerHTML=rows.map(x=>`<article class="domain-card search-item"><span class="index">${x.id} · ${esc(x.group)}</span><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><div class="domain-meta"><span>${esc(x.carrier)}</span><span>→ ${esc(x.next)}</span></div></article>`).join("")||empty();}
function renderPipeline(){$("#pipelineSteps").innerHTML=D.pipeline.map((x,i)=>`<article class="pipeline-step"><span>0${i+1}</span><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join("");}
const pill=e=>`<span class="evidence-pill pill-${e}">${e==='candidate'?'候选':e==='constraint'?'约束':'系统'}</span>`;
function renderModels(){const q=state.query.toLowerCase();$("#modelRows").innerHTML=D.models.filter(x=>(state.model==='all'||x.type===state.model)&&JSON.stringify(x).toLowerCase().includes(q)).map(x=>`<tr class="search-item"><td><strong>${esc(x.name)}</strong></td><td>${esc(x.core)}</td><td>${esc(x.adv)}</td><td>${esc(x.risk)}</td><td>${esc(x.role)}</td><td>${pill(x.evidence)}</td></tr>`).join("")||`<tr><td colspan="6">${empty()}</td></tr>`;}
function renderFormulas(){const cats=["all",...new Set(D.formulas.map(x=>x.cat))];$("#formulaFilter").innerHTML=cats.map(c=>`<option value="${c}" ${state.formula===c?'selected':''}>${c==='all'?'全部公式':c}</option>`).join("");const q=state.query.toLowerCase();$("#formulaGrid").innerHTML=D.formulas.filter(x=>(state.formula==='all'||x.cat===state.formula)&&JSON.stringify(x).toLowerCase().includes(q)).map((x,i)=>`<article class="formula-card search-item" tabindex="0" role="button" data-formula="${D.formulas.indexOf(x)}"><span class="eyebrow">${esc(x.cat)}</span><h3>${esc(x.title)}</h3><div class="equation">${esc(x.eq)}</div><p>${esc(x.meaning)}</p></article>`).join("")||empty();}
function renderTraining(){$("#trainingFlow").innerHTML=D.training.map((x,i)=>`<article class="training-step"><span>${i+1}</span><div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></div></article>`).join("");}
function renderTimeline(){$("#timelineList").innerHTML=D.timeline.map(x=>`<article class="timeline-item"><span>${esc(x.year)}</span><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join("");}
function renderSources(){const types=["all",...new Set(D.sources.map(x=>x.type))];$("#sourceFilter").innerHTML=types.map(t=>`<option value="${t}" ${state.source===t?'selected':''}>${t==='all'?'全部类型':t}</option>`).join("");const q=state.query.toLowerCase();const rows=D.sources.filter(x=>(state.source==='all'||x.type===state.source)&&JSON.stringify(x).toLowerCase().includes(q));$("#sourceCount").textContent=`${rows.length} / ${D.sources.length} 项`;$("#sourceGrid").innerHTML=rows.map(x=>`<a class="source-card search-item" href="${esc(x.url)}" target="_blank" rel="noreferrer"><div class="source-meta"><span>${esc(x.type)}</span><span>${x.year}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.note)}</p><span class="source-link">打开原始来源 ↗</span></a>`).join("")||empty();}
function empty(){return `<div class="empty">没有匹配结果，请更换关键词或筛选条件。</div>`}
function openFormula(i){const x=D.formulas[i],m=$("#formulaModal");$("#modalCategory").textContent=x.cat;$("#modalTitle").textContent=x.title;$("#modalEquation").textContent=x.eq;$("#modalBody").innerHTML=`<h3>推导步骤</h3><ol>${x.derive.map(v=>`<li>${esc(v)}</li>`).join("")}</ol><h3>工程含义</h3><p>${esc(x.meaning)}</p><h3>证据边界</h3><p>${esc(x.boundary)}</p>`;m.hidden=false;document.body.style.overflow="hidden";$(".modal-close").focus();}
function closeModal(){$("#formulaModal").hidden=true;document.body.style.overflow="";}
function renderAll(){renderDomains();renderModels();renderFormulas();renderSources();}
renderPipeline();renderTraining();renderTimeline();renderAll();
document.addEventListener("click",e=>{const d=e.target.closest("[data-domain]");if(d){state.domain=d.dataset.domain;renderDomains()}const mf=e.target.closest("[data-model-filter]");if(mf){state.model=mf.dataset.modelFilter;$$('[data-model-filter]').forEach(b=>b.classList.toggle('active',b===mf));renderModels()}const f=e.target.closest("[data-formula]");if(f)openFormula(+f.dataset.formula);if(e.target.closest("[data-close-modal]"))closeModal();});
document.addEventListener("keydown",e=>{if(e.key==="/"&&!/input|select|textarea/i.test(e.target.tagName)){e.preventDefault();$("#globalSearch").focus()}if(e.key==="Escape"){closeModal();document.body.classList.remove("menu-open")}if((e.key==="Enter"||e.key===" ")&&e.target.matches("[data-formula]")){e.preventDefault();openFormula(+e.target.dataset.formula)}});
$("#globalSearch").addEventListener("input",e=>{state.query=e.target.value.trim();renderAll()});$("#formulaFilter").addEventListener("change",e=>{state.formula=e.target.value;renderFormulas()});$("#sourceFilter").addEventListener("change",e=>{state.source=e.target.value;renderSources()});
$("#themeButton").addEventListener("click",()=>{document.body.classList.toggle("light");localStorage.setItem("g15-theme",document.body.classList.contains("light")?"light":"dark")});if(localStorage.getItem("g15-theme")==="light")document.body.classList.add("light");
$("#menuButton").addEventListener("click",()=>{const open=document.body.classList.toggle("menu-open");$("#menuButton").setAttribute("aria-expanded",String(open))});$$('#nav a').forEach(a=>a.addEventListener('click',()=>document.body.classList.remove('menu-open')));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){$$('#nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${entry.target.id}`))}}),{rootMargin:"-25% 0px -65%"});$$('.anchor-section').forEach(s=>observer.observe(s));
