window.RESEARCH_DATA={
domains:[
{id:"R01",group:"数据",title:"高速视频采集",summary:"帧率、曝光、分辨率、设备和会话身份决定可观察上限。",carrier:"DatasetCollectionPlatform",next:"补充曝光/模糊/球像素尺寸分层统计"},
{id:"R02",group:"数据",title:"TrackMan 对齐",summary:"时间、时区、shot 匹配、OCR review 与结构化球路参数。",carrier:"full211 TrackMan review",next:"确认字段才进入约束与误差"},
{id:"R03",group:"数据",title:"Seed 与人工球心",summary:"首帧 seed、visible center、clear/ignore 与审核并集。",carrier:"V1.1 / V1.2",next:"保持唯一训练真值主线"},
{id:"R04",group:"模型",title:"小快模糊目标",summary:"TrackNet、WASB、高分辨率热图、offset 与 visibility。",carrier:"GolfTrajNet",next:"高分辨率与运动注意力消融"},
{id:"R05",group:"模型",title:"局部 / 全局模型",summary:"全帧身份上下文与 ROI 精细定位的互补融合。",carrier:"golftraj-s / m",next:"统一候选与不确定性契约"},
{id:"R06",group:"视觉",title:"传统像素证据",summary:"帧差、形态学、连通域、亮暗结构和区域配准。",carrier:"OpenCV adapters",next:"作为 direct-pixel gate"},
{id:"R07",group:"跟踪",title:"时序身份连续性",summary:"KLT、Kalman、Viterbi、beam、ROI 与自适应走廊。",carrier:"iterative tracker",next:"分离 observed / predicted"},
{id:"R08",group:"跟踪",title:"起飞状态机",summary:"静止、impact、launch、flight、occluded 与 terminated。",carrier:"V42 / V47",next:"四类反例进入回归门禁"},
{id:"R09",group:"跟踪",title:"遮挡与再捕获",summary:"MISS、协方差扩张、短期预测、终止和像素再捕获。",carrier:"terminal QC",next:"遮挡保持为空"},
{id:"R10",group:"质量",title:"2D 轨迹 QC",summary:"折返、跳点、静止锁、覆盖率、内部缺口与终点连续性。",carrier:"completion QC",next:"质量优先于点数"},
{id:"R11",group:"物理",title:"3D 相机几何",summary:"内外参、针孔投影、尺度约束与重投影误差。",carrier:"Trajectory study",next:"标定不确定性传播"},
{id:"R12",group:"物理",title:"飞行动力学",summary:"重力、平方阻力、Magnus、自旋、风与 RK4。",carrier:"physics/ballistics",next:"Cd/Cl 随工况校准"},
{id:"R13",group:"训练",title:"训练与自训练",summary:"合成预训、真实微调、难例、zero-candidate 与审核闭环。",carrier:"issues 0086—0095",next:"按 shot 分组与反例桶评估"},
{id:"R14",group:"部署",title:"端侧部署",summary:"TorchScript、MPS、Core ML、ANE、在线跟踪和性能预算。",carrier:"GolfBallDetectionApp",next:"真机 parity / latency / memory"},
{id:"R15",group:"质量",title:"审核与可靠性",summary:"逐点证据、210 联系表、断点、哈希和浏览器 QA。",carrier:"issues 0105—0113",next:"完成 V47 全量门禁"},
{id:"R16",group:"外部",title:"外部研究适配",summary:"TrackNet、WASB、TSFMO、TAPIR、CoTracker、PiTrac。",carrier:"OpenSourceAnalysis",next:"只作候选和设计参考"}],
pipeline:[
{title:"采集",text:"高速视频 + 身份元数据"},{title:"对齐",text:"TrackMan / 时间 / shot"},{title:"人工锚点",text:"seed + visible center"},{title:"候选生成",text:"模型 + 传统视觉"},{title:"逐点证据",text:"像素 + 时序 + 冲突"},{title:"状态与 QC",text:"起飞 / 遮挡 / 终止"},{title:"3D 物理",text:"几何 + RK4"},{title:"人工审核",text:"210 条逐视频确认"},{title:"导出",text:"训练或 review-only"}],
models:[
{type:"detector",name:"TrackNet / TrackNetV3",core:"连续帧 → Gaussian heatmap；轨迹修复",adv:"高速微小球专用，利用邻帧",risk:"域偏移；修复点可能无像素支撑",role:"正式模型研究基线",evidence:"candidate"},
{type:"detector",name:"WASB-SBDT",core:"高分辨率特征 + 位置感知训练 + 时序一致性",adv:"跨多种运动数据验证",risk:"仍需 golf 域复现",role:"架构与消融参考",evidence:"candidate"},
{type:"detector",name:"golftraj-s",core:"5 帧共享编码 + Temporal Shift + 运动注意力 + U-Net",adv:"服务器精度优先",risk:"真实数据规模有限",role:"正式服务器模型",evidence:"system"},
{type:"deploy",name:"golftraj-m",core:"15 通道帧堆叠 + 倒残差 U-Net",adv:"ANE 友好、端侧低延迟",risk:"容量与小球细节折中",role:"iPhone Core ML",evidence:"system"},
{type:"tracker",name:"KLT Optical Flow",core:"金字塔 Lucas–Kanade 局部光流",adv:"轻量、直接运动证据",risk:"大位移、模糊、遮挡失效",role:"短时证据 / 反证",evidence:"candidate"},
{type:"tracker",name:"Kalman Filter",core:"状态预测、协方差与观测更新",adv:"不确定性与短缺口传播",risk:"错误观测会强化错误轨迹",role:"搜索窗与预测",evidence:"constraint"},
{type:"tracker",name:"Viterbi / DP",core:"候选∪MISS 的全局最小代价路径",adv:"非贪心、可保留缺帧",risk:"代价设计可偏向静态假点",role:"离线序列解码",evidence:"constraint"},
{type:"tracker",name:"TAPIR",core:"逐帧匹配 + 时序精修 + 可见性",adv:"遮挡与再出现能力",risk:"查询点可能切换到非球物体",role:"研究候选 / 反证",evidence:"candidate"},
{type:"tracker",name:"CoTracker3",core:"联合点跟踪 + 真实视频伪标签",adv:"遮挡与 sim-to-real",risk:"通用点对应不等于球身份",role:"研究候选 / 反证",evidence:"candidate"},
{type:"physics",name:"相机几何 + RK4",core:"针孔重投影 + drag + Magnus 数值积分",adv:"可解释、满足动力学结构",risk:"标定、尺度、Cd/Cl/自旋不确定",role:"3D 约束与校验",evidence:"constraint"},
{type:"physics",name:"LaunchStateEstimator",core:"早期 2D 轨迹 → v₀ / spin / log variance",adv:"可接可微物理和独立监督",risk:"不可用自身预测循环监督",role:"混合 3D 模型",evidence:"system"},
{type:"deploy",name:"Core ML",core:"模型转换 + CPU/GPU/Neural Engine 调度",adv:"隐私、响应与能耗",risk:"算子、数值 parity、内存和热状态",role:"iPhone 17 Pro Max 部署",evidence:"system"}],
formulas:[
{cat:"检测",title:"Gaussian Heatmap",eq:"H(x,y) = exp(-((x-cx)²+(y-cy)²)/(2σ²))",meaning:"将单个球心变成空间概率峰，减轻像素级类别极端不平衡。",derive:["人工中心为 (cx,cy)","用 σ 控制监督半径","argmax 给格点，offset 恢复亚像素"],boundary:"不可把热图高响应直接视作人工标签。"},
{cat:"损失",title:"Penalty-reduced Focal Loss",eq:"Lh = [-Σ(1-p)^α log p·I(y=1) - Σ(1-y)^β p^α log(1-p)·I(y≠1)] / Npos",meaning:"降低简单背景权重，强调小球峰值和困难负样本。",derive:["p = sigmoid(logit)","正样本用 (1-p)^α 聚焦错误峰","高斯邻域负样本由 (1-y)^β 降权"],boundary:"需要与 precision/recall 一起验证，不能只看 loss。"},
{cat:"损失",title:"Masked Offset SmoothL1",eq:"Lo = Σ M·SmoothL1(Δpred-Δgt) / max(ΣM,1)",meaning:"仅在球心格点学习亚像素偏移。",derive:["热图 stride 造成量化","Δgt 是中心在格点内的余量","M=0 的无球帧不计算 offset"],boundary:"错误中心 mask 会直接污染精定位。"},
{cat:"损失",title:"Visibility BCE",eq:"Lv = -[y log σ(z) + (1-y) log(1-σ(z))]",meaning:"独立估计可见性，使定位与有无球解耦。",derive:["z 为可见性 logit","σ(z) 为可见概率","按 visible/occluded/lost 设计标签"],boundary:"occluded 位置可以预测，但不应升级为 observed。"},
{cat:"跟踪",title:"Kalman Predict / Update",eq:"x⁻=Fx; P⁻=FPFᵀ+Q; K=P⁻Hᵀ(HP⁻Hᵀ+R)⁻¹; x=x⁻+K(z-Hx⁻)",meaning:"在观测和运动模型之间按不确定性加权。",derive:["x=[x,y,vx,vy]","F 使用真实 Δt=1/fps","miss 时只扩张 P，不产生观测"],boundary:"预测是搜索先验，不是像素事实。"},
{cat:"跟踪",title:"Viterbi Global Path",eq:"J(path)=Σ Cnode(sₜ)+Σ Ctrans(sₜ₋₁,sₜ)",meaning:"在每帧候选和 MISS 中选择全局最小代价轨迹。",derive:["Cnode=-wc·confidence 或 miss_cost","Ctrans 含位移、速度变化和静止惩罚","动态规划前向累计、反向回溯"],boundary:"MISS 插值必须标 occluded；代价最优不等于球身份正确。"},
{cat:"几何",title:"Pinhole Projection",eq:"Xc=RXw+t; u=fx·Xc/Zc+cx; v=fy·Yc/Zc+cy",meaning:"把 3D 世界轨迹映射到视频像素。",derive:["R,t 完成世界到相机变换","除以深度得到归一化坐标","内参缩放并平移到像素"],boundary:"单像素只给射线；单目深度需要独立约束。"},
{cat:"发射",title:"Launch Velocity",eq:"v₀ = s[cosθ cosφ, sinθ, cosθ sinφ]",meaning:"由球速、仰角和方位角构造三维初速度。",derive:["水平分量为 s cosθ","竖直分量为 s sinθ","水平分量按 φ 分到两个轴"],boundary:"坐标系、角度正方向和单位必须版本化。"},
{cat:"物理",title:"Quadratic Drag",eq:"aD = -(ρ Cd A / 2m) ||v-w||(v-w)",meaning:"相对空气速度越大，阻力近似按速度平方增长。",derive:["动压 q=ρ||vr||²/2","力 FD=qCdA","方向为 -vr_hat；再除以质量"],boundary:"Cd 会随 Reynolds 数和球面结构变化。"},
{cat:"物理",title:"Magnus / Lift",eq:"aM = (ρ Cl A / 2m)||v-w||² fspin · normalize(v̂r × ω̂)",meaning:"自旋与相对气流产生升力/侧向力。",derive:["vr 与自旋轴叉积给方向","Cl 和动压给幅值","fspin 表示自旋强度并限幅"],boundary:"Cl 与 spin 参数并非常数；自旋未知必须表达不确定性。"},
{cat:"物理",title:"RK4 Integration",eq:"sₙ₊₁=sₙ+Δt(k1+2k2+2k3+k4)/6",meaning:"稳定积分位置与速度的非线性微分方程。",derive:["k1=f(sₙ)","k2,k3 在半步估计","k4 在整步估计","加权得到四阶更新"],boundary:"Bezier、样条和 endpoint interpolation 不能替代。"},
{cat:"3D损失",title:"Reprojection Loss",eq:"Lreproj = Σ Mₜ ρ(||π(Xₜ)-pₜ||₂) / ΣMₜ",meaning:"用有效 2D 观测监督物理轨迹。",derive:["RK4 产生 Xₜ","π 投影成像素","仅在 Mₜ=1 比较并用鲁棒 ρ"],boundary:"不可用预测像素监督自身产生的 3D。"},
{cat:"3D损失",title:"TrackMan Relative Loss",eq:"Ltm = mean[((qpred-qtm)/(|qtm|+1))²], q∈{carry,apex,side}",meaning:"统一不同量纲球路标量的相对误差。",derive:["计算物理落点指标","与 confirmed TrackMan 比较","加 1 防止近零不稳定"],boundary:"未确认 OCR/shot 匹配不得进入。"},
{cat:"3D损失",title:"Heteroscedastic NLL",eq:"Lnll = 0.5·mean(exp(-logσ²)(ŷ-y)² + logσ²)",meaning:"同时学习发射量和样本相关不确定性。",derive:["假设高斯观测噪声","网络输出均值与 log variance","高残差与过大方差都受惩罚"],boundary:"不确定性必须做 calibration 检查。"},
{cat:"指标",title:"Point Error / PCK",eq:"e=||ppred-pgt||₂; PCK@τ=mean I(e≤τ)",meaning:"衡量点级定位精度和容差内命中率。",derive:["只对可比较帧计算距离","按阈值 τ 统计命中","按速度/尺寸/场景分层"],boundary:"平均值会掩盖高速末段失败。"},
{cat:"指标",title:"Trajectory Completeness",eq:"coverage=Nobserved/Nexpected; gapmax=max consecutive MISS",meaning:"衡量直接观测覆盖与最大断裂。",derive:["只把真实 observed 计入 numerator","由可见窗口定义 expected","统计最大连续缺失"],boundary:"coverage 必须与折返、跳点、静止锁联合。"}],
training:[
{title:"数据准入",text:"只读人工确认 / 显式验收 labels.csv，并验证 provenance。"},{title:"分组切分",text:"按 session、shot、video 隔离 train / val / test。"},{title:"合成预训练",text:"球、模糊、曝光、背景和物理轨迹；永不进入评估。"},{title:"真实微调",text:"V1.2 reviewed centers + 场景平衡 + hard negatives。"},{title:"联合损失",text:"heatmap focal + offset SmoothL1 + visibility BCE。"},{title:"序列解码",text:"Top-K + Kalman / Viterbi；保留 MISS 与状态。"},{title:"分层评估",text:"点、轨迹、物理、场景、系统五层指标。"},{title:"部署闭环",text:"TorchScript / Core ML parity、延迟、内存、真机 QA。"}],
timeline:[
{year:"V1.0",title:"Pilot20",text:"证明 2D/3D 链路可运行，保留历史基线。"},{year:"V1.1",title:"Seed + TrackMan",text:"建立 210 条上下文和 20 条封存轨迹参考。"},{year:"V1.2",title:"人工球心真值",text:"210 样本、19,696 封存训练点，明确标签边界。"},{year:"V1.3 · Early",title:"模型与自训练",text:"真实训练、zero-candidate 和 completion；单模型闭环暴露风险。"},{year:"V42",title:"可恢复 Full210",text:"210/210 运行完成，但四类用户反例否决视觉正确性。"},{year:"V47 · Now",title:"逐点像素证据",text:"210 多模态复核、证据修正与高速末段恢复。"}],
internalModules:[
{id:"M0",stage:"研究",title:"研究与总结",status:"active / doc-only",fact:"CONTEXT、framework、模块清单与外部研究注册表是当前解释层。",tone:"research"},
{id:"M1",stage:"V1.0",title:"Pilot20",status:"archived baseline",fact:"20 条样本证明早期 2D→3D 链路可运行，只保留历史报告。",tone:"archive"},
{id:"M2",stage:"V1.1",title:"Seed / TrackMan / 轨迹",status:"sealed reference",fact:"210 条 seed 与对齐上下文；strict 3D 200 成功、10 真失败；2D 质量为 155 suspect / 55 broken。",tone:"reference"},
{id:"M3",stage:"V1.2",title:"人工球心真值",status:"canonical",fact:"210 样本；19,696 封存训练点；22,209 当前有效显示点；唯一训练真值主线。",tone:"canonical"},
{id:"M4",stage:"V1.2.1",title:"Gold11 训练证据",status:"archived subset",fact:"11 样本、2,095 点，仅作为派生训练输入证据，不是独立主线。",tone:"archive"},
{id:"M5",stage:"V1.3 / V47",title:"模型、补全与修正",status:"review-only",fact:"V42 全量 171 ready / 33 incomplete / 6 invalid；V47 首审 2 pass / 208 needs correction。",tone:"review"}],
v47Issues:[
{name:"内部可见缺口",value:1296,color:"#58d5c9"},{name:"末段连续性",value:354,color:"#f5bd63"},{name:"错误目标",value:28,color:"#ff8b7b"},{name:"其他",value:7,color:"#7fb6ff"},{name:"中心偏移",value:2,color:"#c8a7ff"}],
biomechTopics:[
{code:"B01",title:"运动学 vs 动力学",tutelman:"位置、速度、加速度描述运动；力和力矩解释原因。",golf15:"视频直接测量 2D 运动学，RK4 表达球飞行动力学。",boundary:"仅凭像素轨迹不能唯一反推人体受力。",url:"https://www.tutelman.com/golf/biomech/concepts1.php#kine"},
{code:"B02",title:"力矩与转动惯量",tutelman:"τ=r×F、τ=Iα；球杆长度增加力臂，也增加转动惯量。",golf15:"杆头轨迹和角/线速度可成为 impact 前观测量。",boundary:"没有人体姿态和受力传感器时，不报告关节力矩。",url:"https://www.tutelman.com/golf/biomech/torque2.php"},
{code:"B03",title:"能量、动量与碰撞",tutelman:"功、动能、角动量和碰撞守恒连接人体做功与球的离开速度。",golf15:"impact/launch 帧、TrackMan 球速与发射状态连接视觉和飞行模型。",boundary:"TrackMan 必须人工确认 shot 匹配后才是强约束。",url:"https://www.tutelman.com/golf/biomech/energy3.php#collisions"},
{code:"B04",title:"坐标系与功能挥杆平面",tutelman:"世界、挥杆平面、球杆坐标系与右手定则；2D 模型存在投影局限。",golf15:"相机内外参、针孔投影、D-plane 与 3D 重投影必须共享版本化坐标契约。",boundary:"单目单点只确定一条射线，深度来自独立约束。",url:"https://www.tutelman.com/golf/biomech/appconcepts2.php#coordinatesystems"},
{code:"B05",title:"Impact model 与 D-plane",tutelman:"目标不只是杆头速度，还包括杆面、路径、击点和挥杆最低点。",golf15:"球与杆头在 impact 邻域的像素证据可连接 launch direction、spin 与 TrackMan。",boundary:"当前 ball-only 轨迹不能替代完整杆面姿态测量。",url:"https://www.tutelman.com/golf/biomech/appconcepts1.php#impactmodel"},
{code:"B06",title:"肌肉、关节与 SSC",tutelman:"肌肉力—速度曲线、拮抗肌、活动范围和 stretch-shortening cycle 限制人体输出。",golf15:"可作为未来人体姿态、分段角速度和伤病风险研究的理论层。",boundary:"当前系统没有肌电、测力台或完整人体骨架，明确标记为未测量。",url:"https://www.tutelman.com/golf/biomech/biology4.php#ssc"}],
sources:[
{type:"论文",year:2019,title:"TrackNet: Tracking High-speed and Tiny Objects",note:"连续帧热图追踪高速微小球。",url:"https://arxiv.org/abs/1907.03698"},
{type:"论文",year:2023,title:"TrackNetV3",note:"增强与轨迹修复。",url:"https://people.cs.nycu.edu.tw/~yushuen/data/TrackNetV3.pdf"},
{type:"代码",year:2023,title:"TrackNetV3 Repository",note:"作者公开实现。",url:"https://github.com/qaz812345/TrackNetV3"},
{type:"论文",year:2023,title:"WASB-SBDT",note:"高分辨率、位置感知与时序一致性。",url:"https://proceedings.bmvc2023.org/310/"},
{type:"代码",year:2023,title:"WASB-SBDT Repository",note:"代码和多运动数据集。",url:"https://github.com/nttcom/WASB-SBDT"},
{type:"论文",year:2022,title:"TSFMO Benchmark",note:"250 序列、26 类运动、20 跟踪器评估。",url:"https://openaccess.thecvf.com/content/ACCV2022/papers/Zhang_Tracking_Small_and_Fast_Moving_Objects_A_Benchmark_ACCV_2022_paper.pdf"},
{type:"代码",year:2022,title:"S-KeepTrack Repository",note:"TSFMO 基线实现。",url:"https://github.com/CodeOfGithub/S-KeepTrack"},
{type:"论文",year:2017,title:"Feature Pyramid Networks",note:"多尺度高层语义与高分辨率融合。",url:"https://openaccess.thecvf.com/content_cvpr_2017/html/Lin_Feature_Pyramid_Networks_CVPR_2017_paper.html"},
{type:"论文",year:2023,title:"TAPIR",note:"逐帧匹配、时序精修与可见性。",url:"https://openaccess.thecvf.com/content/ICCV2023/html/Doersch_TAPIR_Tracking_Any_Point_with_Per-Frame_Initialization_and_Temporal_Refinement_ICCV_2023_paper.html"},
{type:"论文",year:2023,title:"CoTracker",note:"联合点跟踪与遮挡建模。",url:"https://arxiv.org/abs/2307.07635"},
{type:"论文",year:2025,title:"CoTracker3",note:"真实视频伪标签与 sim-to-real。",url:"https://openaccess.thecvf.com/content/ICCV2025/papers/Karaev_CoTracker3_Simpler_and_Better_Point_Tracking_by_Pseudo-Labelling_Real_Videos_ICCV_2025_paper.pdf"},
{type:"官方文档",year:2026,title:"OpenCV Object Tracking",note:"光流、Kalman 和 findTransformECC API。",url:"https://docs.opencv.org/4.x/dc/d6b/group__video__track.html"},
{type:"官方文档",year:2026,title:"OpenCV KalmanFilter",note:"标准预测和校正接口。",url:"https://docs.opencv.org/4.x/dd/d6a/classcv_1_1KalmanFilter.html"},
{type:"论文",year:2022,title:"SoccerNet-Tracking",note:"快速运动、遮挡和长序列 benchmark。",url:"https://openaccess.thecvf.com/content/CVPR2022W/CVSports/papers/Cioppa_SoccerNet-Tracking_Multiple_Object_Tracking_Dataset_and_Benchmark_in_Soccer_Videos_CVPRW_2022_paper.pdf"},
{type:"官方资料",year:2014,title:"USGA Golf Ball Aerodynamics",note:"高尔夫球阻力与升力教学资料。",url:"https://www.usga.org/content/dam/usga/pdf/science-of-golf/middle-school/The%20Ball/aerodynamics_facilitator_guide_MS.pdf"},
{type:"论文",year:2018,title:"Aerodynamics of Golf Balls in Still Air",note:"气动系数、轨迹与 carry。",url:"https://www.mdpi.com/2504-3900/2/6/238"},
{type:"论文",year:2023,title:"Physics + Deep Learning Golf Flight",note:"物理与深度学习混合模拟高尔夫球飞行。",url:"https://openaccess.thecvf.com/content/CVPR2023W/CVSports/papers/McNally_Combining_Physics_and_Deep_Learning_Models_To_Simulate_the_Flight_CVPRW_2023_paper.pdf"},
{type:"官方资料",year:2026,title:"TrackMan 4",note:"双雷达、相机和完整飞行数据参数。",url:"https://www.trackman.com/golf/launch-monitors/trackman-4"},
{type:"官方文档",year:2026,title:"Apple Core ML",note:"CPU/GPU/Neural Engine 端侧推理。",url:"https://developer.apple.com/documentation/coreml"},
{type:"官方视频",year:2024,title:"WWDC24 Core ML Deployment",note:"性能、内存、MLComputePlan 与模型分析。",url:"https://developer.apple.com/videos/play/wwdc2024/10161/"},
{type:"生物力学",year:2020,title:"Tutelman Golf Swing Biomechanics",note:"物理、生物学与挥杆应用教程总入口；作者标注为持续建设中。",url:"https://www.tutelman.com/golf/biomech/index.php"},
{type:"生物力学",year:2020,title:"Torque and Moment of Inertia",note:"力矩、角运动、转动惯量和球杆示例。",url:"https://www.tutelman.com/golf/biomech/torque2.php"},
{type:"生物力学",year:2020,title:"Energy, Momentum and Collision",note:"功、能量、动量与碰撞对高尔夫的解释。",url:"https://www.tutelman.com/golf/biomech/energy3.php"},
{type:"生物力学",year:2020,title:"Golf Swing Coordinate Systems",note:"世界、挥杆平面和球杆坐标系，以及二维模型限制。",url:"https://www.tutelman.com/golf/biomech/appconcepts2.php"},
{type:"项目资料",year:2026,title:"Golf 15 Internal Research",note:"本页内部研究全景：CONTEXT、模块清单、V47 issues 与物理实现。",url:"#internal"},
{type:"项目资料",year:2026,title:"Golf 15 Research Report",note:"可读的完整外部研究报告，不再跳转到父目录乱码路径。",url:"高尔夫追球外部研究报告.md"}]};
